image:
  name: "hashicorp/terraform"
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
- validate
- test

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

validate: 
  stage: validate
  script:
    - terraform validate
  tags:
  - cluster

test:
  stage: test
  script:
  - terraform plan 
  tags:
  - cluster
  dependencies:
  - validate

